stages:
  data_ingestion:
    cmd: python src/MediLeaf_AI/pipeline/stage_01_data_ingestion.py
    deps:
      - src/MediLeaf_AI/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/dataset_v2

  prepare_base_model:
    cmd: python src/MediLeaf_AI/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/MediLeaf_AI/pipeline/stage_02_prepare_base_model.py
      - src/MediLeaf_AI/components/prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
      - PRE_TRAINED_MODEL
      - MONITOR
      - MIN_DELTA
      - PATIENCE
      - MODE
      - RESTORE_BEST_WEIGHTS
      - OPTIMIZER
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/MediLeaf_AI/pipeline/stage_03_training.py
    deps:
      - src/MediLeaf_AI/pipeline/stage_03_training.py
      - src/MediLeaf_AI/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/dataset_v2
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
      - PRE_TRAINED_MODEL


    metrics:
      - artifacts/training/scores/training_scores.json:
          cache: false

    outs:
      - artifacts/training/models/densenet201.keras

  evaluation:
    cmd: python src/MediLeaf_AI/pipeline/stage_04_evaluation.py
    deps:
      - src/MediLeaf_AI/pipeline/stage_04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/dataset_v2
      - artifacts/training/models/densenet201.keras
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
      - PRE_TRAINED_MODEL

    metrics:
      - artifacts/testing/scores/evaluation_scores.json:
          cache: false
