AUGMENTATION: True
PRE_TRAINED_MODEL: MobileNetV2
IMAGE_SIZE: [224, 224, 3] # as per MobileNet V2 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 30
WEIGHTS: imagenet
LEARNING_RATE: 0.001
MONITOR: val_loss
MIN_DELTA: 0.00001
PATIENCE: 20
MODE: auto
RESTORE_BEST_WEIGHTS: False
