AUGMENTATION: True
PRE_TRAINED_MODEL: InceptionV3
IMAGE_SIZE: [300, 300, 3]
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 35
CLASSES: 30
WEIGHTS: imagenet
LEARNING_RATE: 0.001
MONITOR: val_loss
MIN_DELTA: 0.00001
PATIENCE: 20
MODE: auto
RESTORE_BEST_WEIGHTS: False
