AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 19 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 5
CLASSES: 30
WEIGHTS: imagenet
LEARNING_RATE: 0.001
MONITOR: val_loss
MIN_DELTA: 0.00001
PATIENCE: 20
MODE: auto
RESTORE_BEST_WEIGHTS: False