AUGMENTATION: True                # Whether want to to augment the data or not
PRE_TRAINED_MODEL: inceptionv3      # Valid options = [mobilenet, mobilenetv2, nasnetmobile, inceptionv3]
IMAGE_SIZE: [224, 224, 3]         # Input image size taken by models: [height, width, channels]
BATCH_SIZE: 32                    # Batch size for training
INCLUDE_TOP: False
EPOCHS: 35                        # No. of epochs required to train the model
CLASSES: 30                       # No. of classes in the dataset      
WEIGHTS: imagenet                 # Pre-trained weights to be used
LEARNING_RATE: 0.001              # Learning rate for the training
MONITOR: val_loss
MIN_DELTA: 0.00001
PATIENCE: 20
MODE: auto
RESTORE_BEST_WEIGHTS: False
OPTIMIZER: adam                      # Valid options = [adam, sgd, rmsprop, adagrad], Optimizer to be used for training