artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://gitlab.com/surajkarki66/medicinal_plant_leaf_images/-/raw/main/dataset_v2.zip # URL to download the dataset
  local_data_file: artifacts/data_ingestion/dataset_v2.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model/
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated/

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/

training:
  root_dir: artifacts/training
  trained_model_dir: artifacts/training/models
  training_graphs_dir: artifacts/training/graphs
  trained_model_path: artifacts/training/models/
  training_graphs_path: artifacts/training/graphs/